using Microsoft.EntityFrameworkCore.Migrations;

namespace personal_website_api.Migrations
{
    public partial class AddArticles : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Articles"" (
                    ""ArticleId"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""Content"" text NOT NULL,
                    ""Author"" text NOT NULL,
                    ""DateUploaded"" timestamp with time zone NOT NULL,
                    ""DateModified"" timestamp with time zone NOT NULL,
                    ""Active"" boolean NOT NULL,
                    ""Owner"" text NOT NULL,
                    ""LastModifiedUser"" text NOT NULL,
                    ""Views"" integer NOT NULL,
                    ""Title"" text NOT NULL,
                    ""Slug"" text NOT NULL,
                    ""Summary"" text NOT NULL,
                    ""Tags"" text[] NULL,
                    ""SeoTitle"" text NOT NULL,
                    ""SeoDescription"" text NOT NULL,
                    ""SeoKeywords"" text NOT NULL,
                    ""CanonicalUrl"" text NOT NULL,
                    ""SocialImageUrl"" text NOT NULL,
                    CONSTRAINT ""PK_Articles"" PRIMARY KEY (""ArticleId"")
                );
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Articles\";");
        }
    }
}