using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace personal_website_api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
            DO $$
            BEGIN
            IF NOT EXISTS (
                SELECT FROM pg_catalog.pg_tables
                WHERE  schemaname = 'public'
                AND    tablename   = 'Users'
            ) THEN
                CREATE TABLE public.""Users"" (
                ""Id""   integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                ""Name"" text,
                CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );
            END IF;
            END
            $$;");  
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
