name: Build and deploy .NET 8 Azure Function App - my-api-functions-ao-valenzuela

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       # for azure/login
      contents: read        # for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./  

      - name: Publish Azure Function
        run: |
          dotnet publish ./ \
            --configuration Release \
            --framework net8.0 \
            --output ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A86406BA875B4B4BBD7489D77C0E75B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA2A12F5C7CF43B8AC638FFC7AEF8EE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CCC83D0896B4012B1FE6AB5FFE8D77B }}

      - name: Deploy to Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: 'my-api-functions-ao-valenzuela'
          slot-name: 'Production'
          package: './publish'
